server:
  port: 8083
spring:
  application:
    name: server-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration
      - org.redisson.spring.starter.RedissonAutoConfigurationV2
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/dst_servers
    username: ${DB_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:A4s7kQ2xP9mF3vR8}
