bind 0.0.0.0
port 6379
tcp-backlog 511
timeout 300
tcp-keepalive 300

# requirepass 由 CMD 中的 --requirepass 参数覆盖

rename-command FLUSHDB ""
rename-command FLUSHALL ""
rename-command KEYS ""
rename-command CONFIG "REDIS_CONFIG"

save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /data

appendonly yes
appendfsync everysec
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-use-rdb-preamble yes

maxmemory 512mb
maxmemory-policy allkeys-lru

loglevel notice
logfile /data/redis.log

slowlog-log-slower-than 10000
slowlog-max-len 128
